### ISSUE TITLE
Sub-Feature Folders Don't Work

### ISSUE THREAD

**Issue by eldain** [webadvanced/WA-Standards#14]
[How they Are Actually Used](http://www.harecoded.com/organizing-git-branches-in-logical-folders-2317600)

Can't have a branch that acts as both a folder and an actual branch

Unfortunately, it seems like the idea of using `feature--example/subfeature` won't work out. It seems like these are used as a naming convention instead of letting sub features live under an overarching feature. We may want to go back to having sub features branches as outlined in https://github.com/webadvanced/WA-Standards/commit/941873699f6f83864c4b8e2fc3f780b40a16d58a

**Comment by ABonner** [comment]
Well bummer. Seemed like a good idea!
