### ISSUE TITLE
Task / Feature Naming

### ISSUE THREAD

**Issue by ABonner** [webadvanced/WA-Standards#15]
I've seen a number of folks (David Dombrowsky outside our org, and @TimAffeldt inside) name branches like 

JIRA-234-Branch-Purpose

Where `JIRA` is replaced with the Jira shortcode for the project like SCAS.

Seems pretty self explanitory and might be a good way to call "feature" branches for items which we have a solid task in Jira or another system for.

**Comment by TimAffeldt** [comment]
It might be a little cleaner if we keep "feature--" at the front and put the Jira task reference at the end. Something like:

feature--foo-bar-JIRA-123

That would keep all the feautre branches together alpabetically and let us refence the task. We might also have a hotfix on a Jira task.

**Comment by eldain** [comment]
Closed by #18
