### ISSUE TITLE
Branch Restrictions

### ISSUE THREAD

**Issue by eldain** [webadvanced/WA-Standards#5]
Per @caiters comment from Slack, we might also want to lock things down even further by implementing branch restrictions on `master`, `develop`, and `release` branches. Need to put a bit more thought into it, but would prevent direct commits to any of the above, and would have to go through non-restricted `feature` or `hotfix` branches then open a PR to the top level branches. Stricter but that could be a good thing!

**Comment by ABonner** [comment]
Sounds like a great idea!  Its really not hard to make a branch, and we can delete them on GitHub without messing up PR history so our branch list isn't crazy annoying later.

Admins can still force merge if we get into a pickle
